export const ourLatestBlogsStyles = {
  section: 'flex flex-col items-center gap-10 lg:gap-14 px-4 md:px-8 lg:px-10',
  header: 'flex flex-col gap-3 items-center text-center w-full',
  heading: 'text-[var(--text-strong)]',
  card: 'group flex flex-col gap-5 p-4 rounded-3xl flex-shrink-0 w-[288px] md:w-[384px] bg-[var(--surface-primary)] lg:bg-transparent lg:hover:bg-[var(--surface-primary)] transition-colors',
  cardImageWrapper: 'relative w-full aspect-[350/240] rounded-lg overflow-hidden',
  cardImage: 'object-cover',
  cardText: 'flex flex-col gap-2 w-full',
  cardTitle: 'text-[var(--text-strong)] !font-medium',
  cardDescription: 'text-[var(--text-subtle)]',
  cardFooter: 'flex items-center justify-between gap-4 w-full',
  cardBadge: 'flex items-center justify-center px-2 py-1 rounded-lg bg-[var(--surface-subtle)]',
  cardBadgeText: 'text-[var(--text-muted)]',
  cardCta: 'flex items-center gap-1 text-[var(--text-muted)] lg:hidden lg:group-hover:flex',
  cardCtaText: 'text-[var(--text-muted)]',
  cardCtaIcon: 'text-[var(--text-muted)] flex-shrink-0',
} as const
