// Generated by scripts/seo-audit/gen-products.ts — DO NOT hand-edit.
// Product data keyed by page slug, copied verbatim from the legacy site.
export interface RapidProduct {
  name: string
  description?: string
  image?: string
  /** Decimal price string in GBP, e.g. "2.99". */
  price?: string
}

export const RAPID_PRODUCTS: Record<string, RapidProduct> = {
  "business-templates": {
    "name": "Business Document Template Library",
    "description": "Our Business Document Template Library provides professional business documents at your fingertips – in one simple library for only £139.99 per year.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/8b466a46-7c5a-4991-8330-de2bd5687c70.jpg",
    "price": "139.99"
  },
  "company-dissolution": {
    "name": "Company Dissolution Service",
    "description": "If you no longer need a limited company, you can close it by what is known as voluntary company dissolution. This will mean no further annual filings for your company will be required. Rapid Formations provide a dissolution service and all you need to do is electronically sign the application to dissolve your company.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/6cca54d9-b09a-4060-8d54-2c9bc69e46c3.jpg",
    "price": "89.99"
  },
  "company-name-change": {
    "name": "Company Name Change Service",
    "description": "You can change the name of your limited company at any time after incorporation. Rapid Formations provides a professional service to change your company name on your behalf. We will prepare and file the required documentation for a change of name and the process should take no longer than 24 hours to complete.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/223520e1-cac6-4638-ab71-e91eed9ed294.jpg",
    "price": "99.99"
  },
  "confirmation-statement-service": {
    "name": "Confirmation Statement Service",
    "description": "Every limited company or LLP in the UK must file a confirmation statement at Companies House at least once a year. The confirmation statement provides Companies House with confirmation that the company details on the public record are correct and up to date. Rapid Formations provide a confirmation statement filing service, which will ensure you keep your company legal and compliant.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/4e164861-8f5d-49cf-9933-0ef9753081bd.jpg",
    "price": "75.99"
  },
  "director-appointment-resignation": {
    "name": "Director Appointment & Resignation Service",
    "description": "We offer a professional service for clients who wish to appoint or resign directors, including the filing of the Companies House forms and all other paperwork necessary to keep your company records up-to-date and compliant.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/a2b6898a-8cce-40c8-87fa-74babd722c2c.jpg",
    "price": "49.99"
  },
  "dormant-company-accounts": {
    "name": "Dormant Company Accounts Service",
    "description": "If your company is dormant (not trading), you will not be required to submit profit and loss accounts to Companies House. Instead, you can submit a set of 'dormant company accounts'. Rapid Formations provide a dormant company accounts service to new and existing customers, regardless of whether you incorporated your company using our website.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/4af04a1f-7913-41e4-8c45-4050152ccb12.png",
    "price": "49.99"
  },
  "hassle-free-compliance": {
    "name": "Hassle-Free Compliance Service",
    "description": "Save time with legally reviewed business documents, avoid late filings and penalties and get expert compliance support from our Hassle-Free Compliance Service.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/a5dc3544-1787-40f7-9497-0e4cf3d7ad35.jpg",
    "price": "149.99"
  },
  "ico-registration": {
    "name": "ICO Registration",
    "description": "Easily register with the ICO for just £89.99 per year. Get fast, compliant data protection guidance for your business or organisation today.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/511e50bb-fe2b-4ba0-b923-3f39503646a2.jpg",
    "price": "89.99"
  },
  "issue-of-shares": {
    "name": "Issue of Shares Service",
    "description": "This service is for customers who wish to create new shares in their company. Companies can issue shares to both individuals and corporate bodies. We will carry out all the relevant administration to ensure you comply with your filing requirements regarding your issue of shares. If required, we can also file a confirmation statement for your company.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/4814ff1e-f8fe-446f-9456-c7fb482acb31.jpg",
    "price": "129.99"
  },
  "psc-filing": {
    "name": "People with Significant Control Filing",
    "description": "The PSC Filing Service manages all the paperwork required when adding or removing PSCs from Companies House records, or updating their details. £29.99.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/4046ec6a-c0d2-4f54-b475-7ae53e4eb34f.jpg",
    "price": "29.99"
  },
  "transfer-of-shares": {
    "name": "Transfer of Shares Service",
    "description": "This service is for customers who wish to transfer shares from one shareholder to another. Includes Stock Transfer Form, Board Resolution and Share Certificates.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/90e2cadc-1d1b-4c47-9df0-732529c104f0.jpg",
    "price": "129.99"
  },
  "vat-registration": {
    "name": "VAT Registration Service",
    "description": "This service is for customers who would like to register their company for VAT. We will prepare and submit your VAT registration application to HMRC, who take up to 30 days to process applications. Any company that is trading can register for VAT, even if their turnover is less than the VAT threshold of £90,000. Most companies register for VAT on a voluntary basis, as this provides the perception of being an established business with a large turnover.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/669a3989-ce23-457f-ba55-f2094de5dafa.jpg",
    "price": "69.99"
  },
  "business-address": {
    "name": "Business Address Service",
    "description": "Use one of our addresses to receive your company's general business correspondence. We will provide you with a prestigious London business address, enhancing your corporate image and creating an excellent business presence. With this service, you may use our address as the general business contact address for your company and we will forward your business mail to you on the same day we receive it.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/4d276c43-ee8c-4293-8c3b-7e07b3f1639b.png",
    "price": "89.00"
  },
  "london-registered-office": {
    "name": "London Registered Office Service",
    "description": "Use our London Registered Office Address service to protect your home address and use our prestigious Covent Garden address as your company’s registered address. Includes free scan and email mail forwarding.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/f2569576-c232-4c00-b99d-5713994795b8.png",
    "price": "39.00"
  },
  "service-address": {
    "name": "Service Address Service",
    "description": "UK company directors, LLP members, company secretaries, and people with significant control, are legally required to provide a service address for the public record. The primary purpose is for receiving their personal statutory mail and legal documents from official UK government agencies, including Companies House and HMRC. Most of our company formation clients prefer to keep their personal address details confidential, choosing instead to use our London Service Address. This includes the free forwarding of all statutory service address mail to our clients, by scan and email, on a daily basis.",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/3a74d46b-aaa3-41d9-b606-604b3dd04c89.png",
    "price": "26.00"
  },
  "guarantee": {
    "name": "Limited by Guarantee Package",
    "description": "Ideal for clubs, workers' co-operatives and other non-profit organisations . This package provides a company limited by guarantee, and is ideal for all types of not-for-profit enterprises like clubs, sporting associations and membership organisations.  ",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/d31891b2-00da-4cd4-beeb-32740ea107a2.jpg",
    "price": "14.99"
  },
  "llp": {
    "name": "LLP Package",
    "description": "Our Limited Liability Partnership package provides a ready-to-trade LLP, incorporation documents, and a draft LLP Agreement.  ",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/0d0f2f41-dcfd-4f1e-905d-175d342204d6.jpg",
    "price": "19.99"
  },
  "non-residents": {
    "name": "Non-Residents Package",
    "description": "Our Non-Resident Package provides everything you need to set up and trade as a UK limited company.  \n\n- All three address services included \n- Referral to a Wise UK business account ideal for non-residents\n- Hassle Free Compliance Service (worth £149.99)\n\n",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/b92e5318-06a1-4dfa-94e0-1a938cba20d9.jpg",
    "price": "99.99"
  },
  "all-inclusive-package": {
    "name": "All Inclusive Package",
    "description": "#### Recommended for:  \n\n**Growth focused founders**  \n\n- Designed for smart, scalable growth\n- Combines address privacy with a strong business image\n- Includes VAT and PAYE registration\n- Always-on compliance support and instant access to business documents",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/91a0ecc2-a83d-4eb6-b20d-ac5d4daf6935.jpg",
    "price": "39.99"
  },
  "basic-package": {
    "name": "Basic Package",
    "description": "#### Recommended for: \n\n**Basic Formation**  \n\n- Ideal for getting started with no extras",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/beab509f-406c-4a7d-8f38-305a86283110.jpg",
    "price": "2.99"
  },
  "privacy-package": {
    "name": "Privacy Package",
    "description": "#### Recommended for:  \n\n**Protecting your privacy**  \n\n- Keep your home private - register with our Covent Garden address",
    "image": "https://d2zkzcdiu38fde.cloudfront.net/images/b3c4166b-551e-4286-b4b8-760b90ef5ab4.jpg",
    "price": "14.99"
  }
}
