/**
 * Generate src/lib/rapid-products.ts from the harvested legacy Product JSON-LD.
 * Keyed by clone page slug. Exact-parity price/name/description/image copied verbatim
 * from www.rapidformations.co.uk's Product blocks (reports/seo-audit/seo-data.json).
 *
 * Run:  bun scripts/seo-audit/gen-products.ts   (after extract-seo.ts)
 */
interface Pair {
  clonePath: string
  origPath: string
  orig: { jsonLd: { types: string[]; parsed: unknown }[] }
}
const data = JSON.parse(await Bun.file('reports/seo-audit/seo-data.json').text()) as {
  results: Pair[]
}

const slugOf = (p: string) => {
  const parts = p.split('/').filter(Boolean)
  return parts.length ? parts[parts.length - 1] : 'home'
}

const products: Record<string, { name: string; description?: string; image?: string; price?: string }> =
  {}
for (const r of data.results) {
  const block = r.orig.jsonLd.find((l) => l.types.includes('Product'))
  if (!block) continue
  const p = block.parsed as {
    name?: string
    description?: string
    image?: string
    offers?: { priceSpecification?: { price?: string } }[]
  }
  const price = p.offers?.[0]?.priceSpecification?.price
  const slug = slugOf(r.clonePath)
  products[slug] = {
    name: p.name || '',
    ...(p.description ? { description: p.description } : {}),
    ...(p.image ? { image: p.image } : {}),
    ...(price ? { price } : {}),
  }
}

const header = `// Generated by scripts/seo-audit/gen-products.ts — DO NOT hand-edit.
// Product data keyed by page slug, copied verbatim from the legacy site.
export interface RapidProduct {
  name: string
  description?: string
  image?: string
  /** Decimal price string in GBP, e.g. "2.99". */
  price?: string
}

export const RAPID_PRODUCTS: Record<string, RapidProduct> = ${JSON.stringify(products, null, 2)}
`

await Bun.write('src/lib/rapid-products.ts', header)
console.log(`wrote src/lib/rapid-products.ts — ${Object.keys(products).length} products`)
